### ISSUE TITLE
Document Intelligence v4.0

### ISSUE THREAD

**Issue by snakedye** [ai-cfia/fertiscan-backend#40]
Move the the v4.0 API

https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/quickstarts/get-started-sdks-rest-api?view=doc-intel-4.0.0&preserve-view=true&pivots=programming-language-python

## Task

* [ ] Update the dependency
* [ ] Update the tests
* [ ] Use the correct client

## Acceptance Criteria

* The tests should pass
